#!/bin/bash
git clone https://github.com/openstack-dev/devstack.git -b stable/liberty
cp locl.conf devstack
sudo devstack/tools/create-stack-user.sh
mkdir -p /opt/stack
chown -R stack:stack /opt/stack
mv devstack /opt
chown -R stack:stack /opt/devstack
echo Enter password for user "stack"
su stack
/opt/stack/stack.sh
