#!/bin/bash
source /opt/devstack/openrc admin admin
neutron net-create public --shared --provider:physical_network public --provider:network_type flat --router:external True
neutron subnet-create public 10.192.33.0/24 --name public-subnet --allocation-pool start=10.192.33.20,end=10.192.33.254 --dns-nameserver 10.192.33.58 --gateway 10.192.33.1
neutron net-create private --provider:network_type local --shared
neutron subnet-create private --name private-subnet 192.168.0.1/24 --dns-nameserver 10.192.33.58
neutron router-create router1
neutron router-gateway-set router1 public
ssh-keygen -q -N "" -f /opt/stack/.ssh/id_rsa
nova keypair-add --pub-key /opt/stack/.ssh/id_rsa.pub my-key
nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0
nova secgroup-add-rule default tcp 22 22 0.0.0.0/0
