#!/bin/bash

neutron net-create public-network --shared --provider:physical_network External --provider:network_type flat --router:external True
neutron subnet-create public-network 10.64.36.0/22 --name public-subnet --allocation-pool start=10.64.39.1,end=10.64.29.30 --dns-nameserver 10.102.3.50 --gateway 10.64.36.1
neutron net-create pvt-network --provider:network_type vxlan
neutron subnet-create pvt-network --name pvt-subnet 192.168.0.0/24 --dns-nameserver 10.192.33.12
neutron router-create nios-r1
neutron router-gateway-set nios-r1 public-network
neutron router-interface-add nios-r1 pvt-subnet

